language: node_js
node_js:
  - "16.8"

branches:
  only:
    - master

sudo: true

before_script:
  - npm i -g @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: ./dist/content-pusher
  on:
    branch: master
