language: node_js
node_js:
  - "12.11"

branches:
  only:
    - master

sudo: true

before_script:
  - npm i -g @angular/cli@8.3.26

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod --base-href /content-pusher/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/content-pusher
  on:
    branch: master
